version: '3.8'

services:
  web:
    build:
      context: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - "8083:80"  
    depends_on:
      - db
      - nginx  
    networks:
      - my-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8082:80"
    networks:
      - my-network

  nginx:  
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "8080:80"  
    networks:
      - my-network


volumes:
  db_data:

networks:
  my-network:
